vich_uploader:
    db_driver: orm

    mappings:
        media_objects:
            uri_prefix: /media
            upload_destination: '%kernel.project_dir%/public/media'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
